spring.application.name=MessageE2E

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=ngoovzr65qup968u/Z9ivp0cVetkXAqOBxEncVJlntg=
app.jwt.expiration=3600000